# Generated by Django 6.0.1 on 2026-02-04 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LAWYER', 'Lawyer'), ('CLIENT', 'Client')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('state_bar_council', models.CharField(blank=True, max_length=100)),
                ('enrollment_number', models.CharField(blank=True, max_length=50)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('aadhaar', models.CharField(blank=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_cases', to='courtapp.profile')),
                ('lawyer', models.ForeignKey(limit_choices_to={'role': 'LAWYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_cases', to='courtapp.profile')),
            ],
        ),
    ]
